server:
  port: 8045
  
spring:
   data:
    mongodb:
      uri: mongodb://localhost:27017/microservicio01
      
#eureka:
  # client:        
   #  serviceUrl:
    #  defaultZone: http://localhost:8761/eureka 
      
      #https://TU_RUTA-eureka.herokuapp.com/eureka/ 
